---
title: "Report on Berlin CO2 Emissions"
author: "Bhaskar Kamble"
date: "18 Juli 2019"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    theme: united
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
#options(encoding="utf-8")
```



```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source("D:/GITHUB_REPOS/co2emissions/Berlin/mainCO2_Berlin.R")
et_list <- c("erdgas","waerme","fluessiggas","heizoel","holzpellets","strom")

sfh_data <- main_function("SFH" , et_list)
mfh_data <- main_function("MFH" , et_list)
co2_SFH <- sfh_data$co2_emissions#main_function("SFH" , et_list)
co2_MFH <- mfh_data$co2_emissions#main_function("MFH" , et_list)
co2_ALL <- co2_SFH + co2_MFH
co2_ALL$abrechnungsjahr <- 2002:2018
co2_SFH <- co2_SFH/1e9 # in kilo tons
co2_MFH <- co2_MFH/1e9 # in kilo tons
co2_ALL <- co2_ALL/1e9 # in kilo tons
co2_SFH$abrechnungsjahr <- 2002:2018
co2_MFH$abrechnungsjahr <- 2002:2018
co2_ALL$abrechnungsjahr <- 2002:2018
```

```{r}
#co2_MFH
#co2_SFH
```

```{r}
# You must impute average value of CO2 emissions for Strom for the period 2002-2009.
# Ideally you must impute these missing values to the energy consumption and area covered by Strom in the period 2002-2009.
# anyway do it for co2 emissions now.
# 1. Modify CO2_SFH
# 2. Modify CO2_MFH
# Add them to get CO2_ALL like you did in the first code chunk.
co2_SFH$strom[co2_SFH$abrechnungsjahr < 2010] <- mean(co2_SFH$strom[co2_SFH$abrechnungsjahr >2009])
co2_MFH$strom[co2_MFH$abrechnungsjahr < 2010] <- mean(co2_MFH$strom[co2_MFH$abrechnungsjahr >2009])
co2_ALL <- co2_SFH + co2_MFH
co2_ALL$abrechnungsjahr <- 2002:2018
co2_SFH <- getRowSums(co2_SFH[ , names(co2_SFH)!="total"] , dropCols = "abrechnungsjahr")
co2_MFH <- getRowSums(co2_MFH[ , names(co2_MFH)!="total"] , dropCols = "abrechnungsjahr")
co2_ALL <- getRowSums(co2_ALL[ , names(co2_ALL)!="total"] , dropCols = "abrechnungsjahr")
```


```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
co2_MFH_rel <- find_proportions(co2_MFH , c("abrechnungsjahr" , "total"))
co2_MFH_rel <- getRowSums(co2_MFH_rel , "abrechnungsjahr")
co2_SFH_rel <- find_proportions(co2_SFH , c("abrechnungsjahr" , "total"))
co2_SFH_rel <- getRowSums(co2_SFH_rel , "abrechnungsjahr")
co2_ALL_rel <- find_proportions(co2_ALL , c("abrechnungsjahr" , "total"))
co2_ALL_rel <- getRowSums(co2_ALL_rel , "abrechnungsjahr")
```


```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
source("D:/GITHUB_REPOS/co2emissions/Berlin/BezirkAnalysis/getCumSums.R")
co2_SFH_cumsums <- getCumSums(co2_SFH , c("abrechnungsjahr","total"))
co2_MFH_cumsums <- getCumSums(co2_MFH , c("abrechnungsjahr","total"))
co2_ALL_cumsums <- getCumSums(co2_ALL , c("abrechnungsjahr","total"))
co2_SFH_rel_cumsums <- getCumSums(co2_SFH_rel , c("abrechnungsjahr","total"))
co2_MFH_rel_cumsums <- getCumSums(co2_MFH_rel , c("abrechnungsjahr","total"))
co2_ALL_rel_cumsums <- getCumSums(co2_ALL_rel , c("abrechnungsjahr","total"))
```

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#et_list <- names(co2_SFH)[!(names(co2_SFH) %in% c("abrechnungsjahr","total"))]
col_list <- c("royalblue4","orangered1","gray59","orange","blue","olivedrab4")
cols <- c(
          "erdgas"      = "royalblue4",
          "waerme"      = "orangered1",
          "fluessiggas" = "gray59",
          "heizoel"     = "orange",
          "holzpellets" = "blue",
          "strom"       = "olivedrab4"
          )
plot_title <- NULL
order_legend <- rev(c("erdgas","waerme","fluessiggas","heizoel","holzpellets","strom"))
order_labels <- rev(c("Erdgas","Wärme (N+F)","Flüssiggas","Heizöl","Holzpellets","Strom (D+WP)"))
```

```{r}
et_list
```

```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
require(ggplot2)
plot_byET <- function(obj,xlabel,ylabel,plottitle) {
  ggplot()+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[1]),color=et_list[1])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[2]),color=et_list[2])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[3]),color=et_list[3])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[4]),color=et_list[4])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[5]),color=et_list[5])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[6]),color=et_list[6])
  )+scale_color_manual(labels=order_labels,name=" ",values=cols,breaks=order_legend
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[6])),fill=col_list[6]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[5])),fill=col_list[5]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[4])),fill=col_list[4]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[3])),fill=col_list[3]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[2])),fill=col_list[2]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[1])),fill=col_list[1])+theme_bw()+ labs(x=xlabel,y=ylabel,title=plottitle) + theme(plot.title=element_text(size=30), axis.title.x=element_text(size=20, face="bold"), axis.title.y=element_text(size=20, face="bold"), legend.text = element_text(size=15), axis.text.x=element_text(size=15,face="bold"), axis.text.y=element_text(size=15,face="bold"), legend.key.size=unit(2, "lines")
  )+scale_x_continuous(breaks=seq(2002,2018,2))
}
```

# 1. 1-2 Family Houses

copied until line 112 of Berlin_CO2_Emissions_withoutLinearTrend.Rmd in the above.

```{r}
#names(sfh_data)
```

## 1.1. Energy Proportions

```{r}
sfh_data$energy_prop_table
```


```{r}
sfh_data$energy_prop_table <- sfh_data$energy_prop_table[, c("abrechnungsjahr",et_list)]
sfh_data$energy_prop_table
```


```{r}
etPropsCumsum <- getCumSums(sfh_data$energy_prop_table , dropCols="abrechnungsjahr")
etPropsCumsum
```

```{r}
plot_byET(etPropsCumsum , xlabel = "xlabel" , ylabel = "ylabel" , plottitle = NULL)
```





```{r}
require(FNN)
approximate_by_kNN <- function(obj,no_of_neighbors,year_grid) {
  #obj is the data frame of the cumulative co2 emissions (absolute or relative)
  obj_new <- data.frame(abrechnungsjahr=year_grid)
  for (e in names(obj)[names(obj)!="abrechnungsjahr"]) {
    knnr.out <- knn.reg(train=obj$abrechnungsjahr , test=data.frame(abrechnungsjahr=year_grid) , y=obj[[e]] , k=no_of_neighbors)
    #in the above, test can be a finer grid of the abrechnungsjahr (2002 to 2018 in steps of 0.01, for example). 
    #This is the year_grid argument
    #e is looped over the energietraegers
    obj_new[[e]] <- knnr.out$pred
  }
  return(obj_new)
}
neighbors <- 3
```

## 1.3. co2 emissions

```{r}
approximate_by_kNN(co2_SFH_cumsums,no_of_neighbors=neighbors,seq(2002,2018,1))
```



```{r}
#plot_byET(co2_SFH_cumsums , "Jahr" , "kilo t." , NULL)
plot_byET(approximate_by_kNN(co2_SFH_cumsums,no_of_neighbors=neighbors,seq(2002,2018,1)) , "Jahr" , "kilo t." , NULL)
```


