---
title: "Ulm co2 balance all buildings"
author: "Bhaskar Kamble"
date: "1 März 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE)
```

```{r}
setwd("D:/GITHUB_REPOS/co2emissions")
co2_absolut_mfh <- read.csv("./data/ulm/mfh/04_co2_absolut_nachET.csv")
co2_absolut_mfh
co2_absolut_sfh <- read.csv("./data/ulm/sfh/04_co2_absolut_nachET.csv")
co2_absolut_sfh
```


Get the total co2 emissions:
```{r}
is_no_year <- names(co2_absolut_mfh)[names(co2_absolut_mfh)!="abrechnungsjahr"]
co2_absolut_all <- co2_absolut_mfh[,is_no_year] + co2_absolut_sfh[,is_no_year]
co2_absolut_all$abrechnungsjahr <- 2002:2018
co2_absolut_all
```


Make a plot of the total emissions with the linear trend:

```{r}
require(ggplot2)
plot_title <- "Ulm, alle Gebäude (MFH + 1-2 FH)"
linmod <- lm(data=co2_absolut_all,formula=total~abrechnungsjahr)
a <- as.numeric(coefficients(linmod)[1])
b <- as.numeric(coefficients(linmod)[2])
if (a<0) {
  asign <- " "
} else {asign <- "+"}
if (b<0) {
  bsign <- " "
} else {bsign <- " "}
ggplot()+geom_line(data=co2_absolut_all,aes(x=abrechnungsjahr,y=total),color="blue")+geom_point(data=co2_absolut_all,aes(x=abrechnungsjahr,y=total),color="blue")+theme_bw()+labs(x="Jahr",y="1.000 Tonnen",title=plot_title)+ylim(0,max(co2_absolut_all$total))+geom_smooth(method="lm",data=co2_absolut_all,aes(x=abrechnungsjahr,y=total),se=FALSE)+annotate(geom="text",label=paste0(bsign,as.character(round(b,2)),"x",asign,as.character(round(a,0))),x=2008,y=160)+scale_x_continuous(breaks=seq(2002,2018,2))
ggsave("Ulm_all_co2emissions.jpg")
#write.csv2(co2_emissions_kilo_tons_all,file="01_alle_absolut_nachET.csv",row.names = FALSE)
```


#build the cumulative co2 emissions:
```{r}
co2_all_cumsum <- t(apply(co2_absolut_all[, !(names(co2_absolut_all)%in%c("abrechnungsjahr","total"))] 
                                    , 1 , cumsum))
co2_all_cumsum <- as.data.frame(co2_all_cumsum)
co2_all_cumsum$abrechnungsjahr <- 2002:2018
co2_all_cumsum
```

```{r}
datawide <- co2_all_cumsum
datawide
col_list <- c("royalblue4","orangered1","gray59","orange","blue","olivedrab4")
cols <- c(
          "erdgas"      = "royalblue4",
          "waerme"      = "orangered1",
          "fluessiggas" = "gray59",
          "heizoel"     = "orange",
          "holzpellets" = "blue",
          "strom"       = "olivedrab4"
          )
et_list <- c("erdgas","waerme","fluessiggas","heizoel","holzpellets","strom")
order_legend <- rev(c("erdgas","waerme","fluessiggas","heizoel","holzpellets","strom"))
order_labels <- rev(c("Erdgas","Wärme (N+F)","Flüssiggas","Heizöl","Holzpellets","Strom (D+WP)"))
ggplot()+geom_line(data=datawide,aes(x=abrechnungsjahr,y=get(et_list[1]),color=et_list[1])
)+geom_line(data=datawide,aes(x=abrechnungsjahr,y=get(et_list[2]),color=et_list[2])
)+geom_line(data=datawide,aes(x=abrechnungsjahr,y=get(et_list[3]),color=et_list[3])
)+geom_line(data=datawide,aes(x=abrechnungsjahr,y=get(et_list[4]),color=et_list[4])
)+geom_line(data=datawide,aes(x=abrechnungsjahr,y=get(et_list[5]),color=et_list[5])
)+geom_line(data=datawide,aes(x=abrechnungsjahr,y=get(et_list[6]),color=et_list[6])
)+scale_color_manual(labels=order_labels,name=" ",values=cols,breaks=order_legend
)+geom_ribbon(data=datawide,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[6])),fill=col_list[6]
)+geom_ribbon(data=datawide,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[5])),fill=col_list[5]
)+geom_ribbon(data=datawide,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[4])),fill=col_list[4]
)+geom_ribbon(data=datawide,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[3])),fill=col_list[3]
)+geom_ribbon(data=datawide,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[2])),fill=col_list[2]
)+geom_ribbon(data=datawide,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[1])),fill=col_list[1])+theme_bw()+ labs(x="Jahr",y="1.000 Tonnen",title=plot_title
)+scale_x_continuous(breaks=seq(2002,2018,2))
#ggsave("Ulm_all_co2emissions_absolute_nachET.jpg")
#write.csv2(datawide , "02_alle_absolut_nachET_kumulativ.csv",row.names=FALSE)
```


```{r}
datawide
```

```{r}
co2_anteile <- as.data.frame(sapply(datawide[,names(datawide)!="abrechnungsjahr"] , function(obj) obj/datawide$strom)) 
co2_anteile$abrechnungsjahr <- 2002:2018
co2_anteile
```


```{r}
ggplot()+geom_line(data=co2_anteile,aes(x=abrechnungsjahr,y=get(et_list[1]),color=et_list[1])
)+geom_line(data=co2_anteile,aes(x=abrechnungsjahr,y=get(et_list[2]),color=et_list[2])
)+geom_line(data=co2_anteile,aes(x=abrechnungsjahr,y=get(et_list[3]),color=et_list[3])
)+geom_line(data=co2_anteile,aes(x=abrechnungsjahr,y=get(et_list[4]),color=et_list[4])
)+geom_line(data=co2_anteile,aes(x=abrechnungsjahr,y=get(et_list[5]),color=et_list[5])
)+geom_line(data=co2_anteile,aes(x=abrechnungsjahr,y=get(et_list[6]),color=et_list[6])
)+scale_color_manual(labels=order_labels,name=" ",values=cols,breaks=order_legend
)+geom_ribbon(data=co2_anteile,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[6])),fill=col_list[6]
)+geom_ribbon(data=co2_anteile,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[5])),fill=col_list[5]
)+geom_ribbon(data=co2_anteile,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[4])),fill=col_list[4]
)+geom_ribbon(data=co2_anteile,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[3])),fill=col_list[3]
)+geom_ribbon(data=co2_anteile,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[2])),fill=col_list[2]
)+geom_ribbon(data=co2_anteile,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[1])),fill=col_list[1])+theme_bw()+ labs(x="Jahr",y="Anteile in Prozent",title=plot_title
)+scale_x_continuous(breaks=seq(2002,2018,2))
#ggsave("Ulm_all_co2emissions_relative_nachET.jpg")
#write.csv2(co2_anteile , "03_alle_relativ_nachET_kumulativ.csv",row.names=FALSE)
```


```{r}
totalArea <- read.csv("Ulm_wohngebaeude_zahl_flaeche.csv",sep=";")
totalArea$totArea <- totalArea$Flaeche_MFH + totalArea$Flaeche_SFH
totalArea <- totalArea[ , c("Year","totArea")]
names(totalArea) <- c("Abrechnungsjahr","totArea")
totalArea
```


Specific CO2 emissions:

```{r}
spez_co2_emission <- data.frame(abrechnungsjahr = 2002:2018 , spez_co2 = 1e6* co2_absolut_all$total/totalArea$totArea) #0.001*rowSums(co2_emissions)/totalArea$totArea)
spez_co2_emission
```


```{r}
linmod_spez <- lm(data=spez_co2_emission,formula=spez_co2~abrechnungsjahr)
a_spez <- as.numeric(coefficients(linmod_spez)[1])
b_spez <- as.numeric(coefficients(linmod_spez)[2])
if (a_spez<0) {
  asign_spez <- " "
} else {asign_spez <- "+"}
if (b_spez<0) {
  bsign_spez <- " "
} else {bsign_spez <- " "}
ggplot()+geom_line(data=spez_co2_emission,aes(x=abrechnungsjahr,y=spez_co2),color="blue")+geom_point(
  data=spez_co2_emission,aes(x=abrechnungsjahr,y=spez_co2),color="blue")+theme_bw()+labs(x="Jahr",
  y="kg/qm",title=plot_title)+ylim(0,max(spez_co2_emission$spez_co2))+geom_smooth(
  method="lm",data=spez_co2_emission,aes(x=abrechnungsjahr,y=spez_co2),se=FALSE)+annotate(
  geom="text",label=paste0(bsign_spez,as.character(round(b_spez,2)),"x",asign_spez,as.character(round(a_spez,0))
  ),x=2012,y=30)+scale_x_continuous(breaks=seq(2002,2018,2))
#ggsave("Ulm_co2_spez.jpg")
#write.csv2(spez_co2_emission , "04_alle_co2_spez.csv",row.names=FALSE)
```


```{r}
et_list
```

```{r}
et_list
co2cumsums_linear <- datawide
storage_co2 <- list()
for (et in et_list) {
  storage_co2[[et]] <- lm(get(et) ~ abrechnungsjahr , data = datawide)
}
for (et in et_list) {
  co2cumsums_linear[[et]] <- predict(storage_co2[[et]] , newdata = datawide)
}


storage_co2_anteile <- list()
co2anteile_cumsums_linear <- co2_anteile
for (et in et_list) {
  storage_co2_anteile[[et]] <- lm(get(et) ~ abrechnungsjahr , data = co2_anteile)
}
for (et in et_list) {
  co2anteile_cumsums_linear[[et]] <- predict(storage_co2_anteile[[et]] , newdata = co2_anteile)
}
```


```{r}
ggplot()+geom_line(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[1]),color=et_list[1])
)+geom_line(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[2]),color=et_list[2])
)+geom_line(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[3]),color=et_list[3])
)+geom_line(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[4]),color=et_list[4])
)+geom_line(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[5]),color=et_list[5])
)+geom_line(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[6]),color=et_list[6])
)+scale_color_manual(labels=order_labels,name=" ",values=cols,breaks=order_legend
)+geom_ribbon(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[6])),fill=col_list[6]
)+geom_ribbon(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[5])),fill=col_list[5]
)+geom_ribbon(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[4])),fill=col_list[4]
)+geom_ribbon(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[3])),fill=col_list[3]
)+geom_ribbon(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[2])),fill=col_list[2]
)+geom_ribbon(data=co2anteile_cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[1])),fill=col_list[1]
)+theme_bw()+ labs(x="Jahr",y="CO2 Anteile",title=plot_title)+scale_x_continuous(breaks=seq(2002,2018,2))
#ggsave("Ulm_CO2_anteile_all_linear.jpg")
#write.csv2(co2anteile_cumsums_linear , "05_alle_relativ_nachET_kumulativ_linear.csv",row.names=FALSE)
```


```{r}
ggplot()+geom_line(data=co2cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[1]),color=et_list[1])
)+geom_line(data=co2cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[2]),color=et_list[2])
)+geom_line(data=co2cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[3]),color=et_list[3])
)+geom_line(data=co2cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[4]),color=et_list[4])
)+geom_line(data=co2cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[5]),color=et_list[5])
)+geom_line(data=co2cumsums_linear,aes(x=abrechnungsjahr,y=get(et_list[6]),color=et_list[6])
)+scale_color_manual(labels=order_labels,name=" ",values=cols,breaks=order_legend
)+geom_ribbon(data=co2cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[6])),fill=col_list[6]
)+geom_ribbon(data=co2cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[5])),fill=col_list[5]
)+geom_ribbon(data=co2cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[4])),fill=col_list[4]
)+geom_ribbon(data=co2cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[3])),fill=col_list[3]
)+geom_ribbon(data=co2cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[2])),fill=col_list[2]
)+geom_ribbon(data=co2cumsums_linear,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[1])),fill=col_list[1]
)+theme_bw()+ labs(x="Abrechnungsjahr",y="kilo tonne",title=plot_title)+scale_x_continuous(breaks=seq(2002,2018,2))
#ggsave("Ulm_CO2_absolute_all_linear.jpg")
#write.csv2(co2cumsums_linear , "06_alle_absolut_nachET_kumulativ_linear.csv",row.names=FALSE)
```


























































































































