---
title: "CO<sub>2</sub> emissions for Ulm"
author: "Bhaskar Kamble"
date: "4 März 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,cache=FALSE,message=FALSE)
```

## Introduction

CO<sub>2</sub> emissions for Ulm...

```{r}
setwd("D:/GITHUB_REPOS/co2emissions")
load("MFH20022018_v2.RData")
load("SFH20022018_v2.RData")
#In SFH20022018, abrechnungsjahr and verbrauch_gesamt_kwh are character - change then to int and numeric
SFH20022018$abrechnungsjahr <- as.integer(SFH20022018$abrechnungsjahr)
SFH20022018$verbrauch_gesamt_kwh <- gsub("," , "." , SFH20022018$verbrauch_gesamt_kwh)
SFH20022018$verbrauch_gesamt_kwh <- as.numeric(SFH20022018$verbrauch_gesamt_kwh)
SFH20022018$gtype <- "SFH"
MFH20022018$gtype <- "MFH"
```

```{r}
find_ET_shares_by_year <- function(inputdata) {
  require(dplyr)
  by_year_ET <- group_by(inputdata,abrechnungsjahr,energietraeger)
  return(as.data.frame(summarize(by_year_ET,sum(verbrauch_gesamt_kwh))))
  detach(package:dplyr)
}

find_et_list <- function(inputdata) {
  ET_list <- unique(inputdata$energietraeger)  
  return(ET_list)
}
subset_data_by_region <- function(inputdata , region) {
  outputdata <- inputdata[inputdata$Landkreis_von_GS == region , ]
  return(outputdata)
}
readweather <- function(filename) {
  weather_data <- read.csv(filename,header=TRUE , sep=";" , dec="," )
  names(weather_data) <- c("Year","wind","sun","bedeckung","temperatur")
  no_of_years <- 17
  if (dim(weather_data)[1] != no_of_years) {
    stop("check number of years in weather data")
  }
  return(weather_data)
}
```

```{r}
weather_ulm <- readweather("ulm_weather.csv")
ulm_sfh <- subset_data_by_region(SFH20022018,"Ulm")
ulm_sfh$energietraeger[ulm_sfh$energietraeger=="fernwaerme"] <- "waerme"
ulm_sfh$energietraeger[ulm_sfh$energietraeger=="nahwaerme"] <- "waerme"
ulm_sfh$energietraeger[ulm_sfh$energietraeger=="waermepumpe"] <- "strom"
et_list <- find_et_list(ulm_sfh)
```







## Ulm, 1-2 FH






## Verbrauchsanteile der Energieträger

```{r}
#get the data:
ET_shares_by_year <- find_ET_shares_by_year(ulm_sfh)
names(ET_shares_by_year) <- c("abrechnungsjahr" ,"energietraeger" ,"sum_verbrauch_gesamt_kwh")
#change to wide format
detach(package:dplyr)
require(reshape2)
ET_shares_by_year_wide <- dcast(ET_shares_by_year , abrechnungsjahr ~ energietraeger , value.var = "sum_verbrauch_gesamt_kwh")
ET_shares_by_year_wide[is.na(ET_shares_by_year_wide)]=0.0
drop_cols <- "abrechnungsjahr"
ET_shares_by_year_wide$Yearlysum <- rowSums(ET_shares_by_year_wide[ , !(names(ET_shares_by_year_wide) %in% drop_cols)])
detach(package:reshape2)
```

```{r}
drop_cols <- c("abrechnungsjahr","Yearlysum")
final_prop_table <- as.data.frame(sapply(ET_shares_by_year_wide[ , !(names(ET_shares_by_year_wide) %in% drop_cols)],function(obj) obj/ET_shares_by_year_wide$Yearlysum))
final_prop_table$abrechnungsjahr <- 2002:2018
```



```{r}
library(gridExtra)
library(grid)
#mytheme <- gridExtra::ttheme_default(
#    core = list(fg_params=list(cex = 2.0)),
#    colhead = list(fg_params=list(cex = 1.0)),
#    rowhead = list(fg_params=list(cex = 1.0)))
```





```{r}
FRP_round <- data.frame ( sapply ( final_prop_table[ , c("abrechnungsjahr" , names(final_prop_table)[names(final_prop_table)!="abrechnungsjahr"])] , function(obj) round(obj,2)))
FRP_round <- FRP_round[,c("abrechnungsjahr","erdgas","waerme","fluessiggas","heizoel","holzpellets","strom")]
names(FRP_round) <- c("Jahr","Erdgas","Wärme","Flüssiggas","Heizöl","Holzpellets","Strom")
grid.draw(tableGrob(FRP_round,theme=ttheme_minimal(base_size = 8)))
```





```{r}
final_prop_table <- final_prop_table[,c("erdgas","waerme","fluessiggas","heizoel","holzpellets","strom","abrechnungsjahr")]
final_prop_table_cumsums <- t(apply(final_prop_table[, !(names(final_prop_table)=="abrechnungsjahr")] 
                                    , 1 , cumsum))
final_prop_table_cumsums <- as.data.frame(final_prop_table_cumsums)
final_prop_table_cumsums$abrechnungsjahr <- final_prop_table$abrechnungsjahr
```


```{r}
#final_prop_table_cumsums_omit2018 <- final_prop_table_cumsums[final_prop_table_cumsums$abrechnungsjahr!=2018 , ]
et_list <- names(final_prop_table_cumsums)[names(final_prop_table_cumsums)!="abrechnungsjahr"]
storage <- list()
for (et in et_list) {
  storage[[et]] <- lm(get(et) ~ abrechnungsjahr , data = final_prop_table_cumsums)
}
for (et in et_list) {
  colname <- paste0(et,"_lm")
  final_prop_table_cumsums[[colname]] <- predict(storage[[et]] , newdata = final_prop_table_cumsums)
}#in the predictions, replace any negative numbers by zeros
#final_prop_table_cumsums
```


```{r}
slopes <- NULL
intercepts <- NULL
for (et in et_list) {
  intercepts <- c(intercepts , as.numeric(coefficients(storage[[et]])[1]))
  slopes <- c(slopes , as.numeric(coefficients(storage[[et]])[2]))
}
```

```{r}
datawide <- final_prop_table_cumsums
datawide[,names(datawide)!="abrechnungsjahr"] <- 100.0*datawide[,names(datawide)!="abrechnungsjahr"]
col_list <- c("royalblue4","orangered1","gray59","orange","blue","olivedrab4")
cols <- c(
          "erdgas"      = "royalblue4",
          "waerme"      = "orangered1",
          "fluessiggas" = "gray59",
          "heizoel"     = "orange",
          "holzpellets" = "blue",
          "strom"       = "olivedrab4"
          )
plot_title <- "Ulm, 1-2 FH"
order_legend <- rev(c("erdgas","waerme","fluessiggas","heizoel","holzpellets","strom"))
order_labels <- rev(c("Erdgas","Wärme (N+F)","Flüssiggas","Heizöl","Holzpellets","Strom (D+WP)"))
```

```{r}
require(ggplot2)
plot_byET <- function(obj,xlabel,ylabel,plottitle) {
  ggplot()+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[1]),color=et_list[1])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[2]),color=et_list[2])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[3]),color=et_list[3])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[4]),color=et_list[4])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[5]),color=et_list[5])
  )+geom_line(data=obj,aes(x=abrechnungsjahr,y=get(et_list[6]),color=et_list[6])
  )+scale_color_manual(labels=order_labels,name=" ",values=cols,breaks=order_legend
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[6])),fill=col_list[6]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[5])),fill=col_list[5]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[4])),fill=col_list[4]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[3])),fill=col_list[3]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[2])),fill=col_list[2]
  )+geom_ribbon(data=obj,aes(x=abrechnungsjahr,ymin=0,ymax=get(et_list[1])),fill=col_list[1])+theme_bw()+ labs(x=xlabel,y=ylabel,title=plottitle
  )+scale_x_continuous(breaks=seq(2002,2018,2))
}
```











## Verbrauchsanteile der Energieträger

```{r}
plot_byET(datawide,"Jahr","Anteile in Prozent", "Verbrauchsanteile der Energieträger, Ulm, 1-2 FH")
```












## Flächeanteile der Energieträger

```{r}
require(dplyr)
by_year_ETArea <- group_by(ulm_sfh,abrechnungsjahr,energietraeger)
ET_areas_by_year <- as.data.frame(summarize(by_year_ETArea,sum(gebaeude_nutzflaeche)))
names(ET_areas_by_year) <- c("abrechnungsjahr" ,"energietraeger" ,"sum_nutzflaeche")
#change to wide format
detach(package:dplyr)
library(reshape2)
ET_areas_by_year_wide <- dcast(ET_areas_by_year , abrechnungsjahr ~ energietraeger , value.var = "sum_nutzflaeche")
ET_areas_by_year_wide[is.na(ET_areas_by_year_wide)]=0.0
drop_cols <- "abrechnungsjahr"
ET_areas_by_year_wide$Yearlysum <- rowSums(ET_areas_by_year_wide[ , !(names(ET_areas_by_year_wide) %in% drop_cols)])
drop_cols <- c("abrechnungsjahr","Yearlysum")
area_prop_table <- as.data.frame(sapply(ET_areas_by_year_wide[ , !(names(ET_areas_by_year_wide) %in% drop_cols)],function(obj) obj/ET_areas_by_year_wide$Yearlysum))
area_prop_table$abrechnungsjahr <- 2002:2018
area_prop_table
```

